### ISSUE TITLE
Colds: steel Mod incompatiblity 

### ISSUE THREAD

**Issue by Mr-Syntax** [TheIllusiveC4/Champions#85]
Im running forge 36.1.10 and minecraft 1.16.5 

[09:28:55] [Server thread/ERROR]: Exception caught during firing event: top.theillusivec4.champions.common.entity.EnkindlingBulletEntity cannot be cast to net.minecraft.entity.LivingEntity
	Index: 3
	Listeners:
		0: HIGHEST
		1: ASM: class com.github.clevernucleus.playerex.init.EventHandler onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		2: NORMAL
		3: ASM: class com.coldspell.coldsteel.abilities.OnHurtEntity onHurtEffect(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		4: ASM: class tallestegg.guardvillagers.HandlerEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		5: ASM: class com.majruszs_difficulty.events.when_damaged.WhenDamagedEvent onAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		6: ASM: class com.majruszs_difficulty.events.treasure_bag.UpdatePlayerList onHit(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		7: ASM: class net.silentchaos512.scalinghealth.event.PlayerBonusRegenHandler onPlayerHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		8: ASM: class cursedflames.bountifulbaubles.common.baubleeffect.EventHandlerEffect onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		9: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@4b126e4c onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		10: ASM: class com.teammetallurgy.aquaculture.misc.NeptunesMight onAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		11: ASM: class com.teammetallurgy.atum.items.artifacts.atem.AtemsProtectionItem onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		12: ASM: class com.teammetallurgy.atum.items.artifacts.seth.SethsStingItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		13: ASM: class com.teammetallurgy.atum.items.artifacts.nuit.NuitsIreItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		14: ASM: class com.teammetallurgy.atum.items.artifacts.nuit.NuitsQuarterItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		15: ASM: class com.teammetallurgy.atum.items.artifacts.anubis.AnubisWrathItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		16: ASM: class com.teammetallurgy.atum.items.artifacts.nepthys.NepthysGuardItem onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		17: ASM: class com.teammetallurgy.atum.items.artifacts.nepthys.NepthysConsecrationItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		18: ASM: class com.teammetallurgy.atum.items.artifacts.nepthys.NepthysBanishingItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		19: ASM: class com.teammetallurgy.atum.items.artifacts.geb.GebsUndoingItem onAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		20: ASM: class com.teammetallurgy.atum.items.tools.GauntletItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		21: ASM: class com.teammetallurgy.atum.items.tools.ClubItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		22: ASM: class com.teammetallurgy.atum.items.tools.HammerItem onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		23: ASM: class com.teammetallurgy.atum.misc.event.AtumEventListener onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		24: ASM: class com.teammetallurgy.atum.entity.projectile.PharaohOrbEntity onBerserk(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		25: ASM: class chumbanotz.mutantbeasts.EventHandler onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		26: ASM: class insane96mcp.progressivebosses.events.LivingHurt eventLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		27: ASM: class com.baguchan.enchantwithmob.CommonEventHandler onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		28: ASM: class com.oblivioussp.spartanweaponry.event.CommonEventHandler onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		29: ASM: class com.infamous.dungeons_mobs.MobEvents onSnowballDamageMob(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		30: ASM: class twilightforest.TFEventListener entityHurts(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		31: ASM: class twilightforest.item.ItemTFMinotaurAxe onAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		32: ASM: class quek.undergarden.item.tool.UGSwordItem attackEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		33: ASM: class quek.undergarden.item.tool.UGShovelItem attackEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		34: ASM: class quek.undergarden.item.tool.UGPickaxeItem attackEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		35: ASM: class quek.undergarden.item.tool.UGAxeItem attackEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		36: ASM: net.mcreator.villageemployment.procedures.WhenPlayerIsHurtProcedure@2da70c4 onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		37: ASM: class slimeknights.tconstruct.shared.AchievementEvents onDamageEntity(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		38: ASM: class com.danny.dannys_expansion.core.events.HurtEventHandler hurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		39: ASM: top.theillusivec4.champions.common.ChampionEventsHandler@4decc78a onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		40: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@18d66618 onEntityDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		41: LOW
		42: ASM: org.jwaresoftware.mcmods.lib.impl.effects.NourishmentEffectsEventsHandler@531c9a66 onEntityDamagedByTHE(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
java.lang.ClassCastException: top.theillusivec4.champions.common.entity.EnkindlingBulletEntity cannot be cast to net.minecraft.entity.LivingEntity
	at com.coldspell.coldsteel.abilities.OnHurtEntity.onHurtEffect(OnHurtEntity.java:26)
	at net.minecraftforge.eventbus.ASMEventHandler_18_OnHurtEntity_onHurtEffect_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2622/498439173.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362)
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1472)
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984)
	at top.theillusivec4.champions.common.entity.EnkindlingBulletEntity.bulletEffect(EnkindlingBulletEntity.java:35)
	at top.theillusivec4.champions.common.entity.AbstractBulletEntity.bulletHit(AbstractBulletEntity.java:335)
	at top.theillusivec4.champions.common.entity.AbstractBulletEntity.func_70071_h_(AbstractBulletEntity.java:255)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.server.ServerWorld$$Lambda$31552/998685353.accept(Unknown Source)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$30430/162565732.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[09:28:55] [Server thread/FATAL]: Preparing crash report with UUID 6f98f246-b1f5-4727-824f-6375c8099624
[09:28:55] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$30430/162565732.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassCastException: top.theillusivec4.champions.common.entity.EnkindlingBulletEntity cannot be cast to net.minecraft.entity.LivingEntity
	at com.coldspell.coldsteel.abilities.OnHurtEntity.onHurtEffect(OnHurtEntity.java:26) ~[?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_18_OnHurtEntity_onHurtEffect_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2622/498439173.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1472) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?]
	at top.theillusivec4.champions.common.entity.EnkindlingBulletEntity.bulletEffect(EnkindlingBulletEntity.java:35) ~[?:task ':jar' property 'archiveVersion']
	at top.theillusivec4.champions.common.entity.AbstractBulletEntity.bulletHit(AbstractBulletEntity.java:335) ~[?:task ':jar' property 'archiveVersion']
	at top.theillusivec4.champions.common.entity.AbstractBulletEntity.func_70071_h_(AbstractBulletEntity.java:255) ~[?:task ':jar' property 'archiveVersion']
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$31552/998685353.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more

**Comment by TheIllusiveC4** [comment]
This is on the Colds: Steel mod's end and I believe they've fixed it already.

**Comment by Mr-Syntax** [comment]
he did :) but thanks for the reply
